[theme]
primaryColor = "#ffad1f"
backgroundColor = "#0a1628"
secondaryBackgroundColor = "#0d2240"
textColor = "#e8edf5"
font = "sans serif"

[server]
# Permet de charger des fichiers Excel/CSV plus lourds (50 Mo)
maxUploadSize = 50
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
# Masque le menu "Deploy", "Record", etc., pour un look "Logiciel Pro"
gatherUsageStats = false
toolbarMode = "minimal"

[client]
# Masque les détails techniques des erreurs pour les utilisateurs
showErrorDetails = false
